version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # 將主機端口從 80 改為 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - "8081:80"  # 將主機端口從 8080 改為 8081
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

